"""add table users

Revision ID: 3813c67be6c4
Revises: 11f16b5a4b7c
Create Date: 2023-06-24 14:53:10.938054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3813c67be6c4'
down_revision = '11f16b5a4b7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FVA_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=300), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('FVA_users')
    # ### end Alembic commands ###